GET http://localhost:8080/user/1
accept: */*
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyU2VxIjoxLCJ1c2VySWQiOiJtZWxsb3dfcEBuYXZlci5jb20iLCJ1c2VyVHlwZSI6MCwidXNlclN0YXR1cyI6MCwic3ViIjoibWVsbG93X3BAbmF2ZXIuY29tIiwiaWF0IjoxNjMxMDk2NTI0LCJleHAiOjE2MzEwOTgzMjR9.--BCeKHj0L2RI73KuRcEh3QvDSEIkE3vTcWxMNv-_n8
Content-Type: application/json
